@startuml

enum TaxiStatus {
  IN_ROUTE_TO_PICKUP
  PICKUP
  IN_ROUTE_TO_DROPOFF
  DROPOFF
  ROAMING
}

abstract class Person {
  +id: uuid
  +name: string
  +phoneNumber: string
}

class Passenger extends Person {
}

class Dispatcher extends Person {
}

struct RideRequest {
  +id: uuid
  +passenger: Passenger
  +currentLocation: Location
  +destination: Location
}

struct Location {
  +name: string
  +latitude: double
  +longitude: double
}

node WebApplication {
}

Dispatcher -> RideRequest : "Enter/Remove a ride request"
RideRequest -> WebApplication

class Scheduler {
  -rideRequests: std::priority_queue<RideRequest>
  -fleetState: std::priority_queue<VehicleState>
  +addRideRequests(rideRequest: RideRequest): void
  +updateFleetStates(): void
  +assignTaxiToRideRequest(): std::pair<uuid, uuid> // <vehicleId, rideRequestId>
}

struct Route {
  +id: uuid
  +startLocation: Location
  +endLocation: Location
  +waypoints: std::vector<Location>
}

Route -> Location

class Router {
  -map: Map
  -laneGraph: LaneGraph
  +generateRoute(startLocation: Location, endLocation: Location): Route
  +getWaitTime(curLocation: Location, startLocation: Location): double
  {static} getTravelTime(route: Route): double
}

Router -> Route : "Generate route"

class PassengerTracker {
  -passengerStates: std::unordered_map<uuid, PassengerState>
  -passengerVehicleMap: std::unordered_map<uuid, uuid> // <passengerId, vehicleId>
  +getLocation(passengerId: uuid): Location
  +getWaitTime(passengerId: uuid): uuid): double
  +getTravelTime(passengerId: uuid): uuid): double
}

class FleetStateTracker {
  +vehicleStates: std::unordered_map<uuid, VehicleState>
  +queryVehicleState(vehicleId: uuid): VehicleState
  +getLocation(vehicleId: uuid): Location
  +getSpeed(vehicleId: uuid): double
  +getOperationStage(vehicleId: uuid): TaxiStatus
}

database Database {
'  +data: Map<string, List<Record>>
'  +readData(query: string): List<Record>
'  +writeData(record: Record): void
}

artifact Robotaxi {
}

class Vehicle {
  -vehicleState: VehicleState
  -route: Route
  +acceptRideRequest(route: Route): bool
  +executeRideRequest(): void
}

struct VehicleState {
  +id: uuid
  +curLocation: Location
  +speed: double
  +taxiStatus: TaxiStatus
}

Robotaxi --> Vehicle : has a system
Vehicle -> VehicleState

class Commander {
  -routeList: std::vector<std::pair<uuid, Route>>
  +callRouter(vehicleRequestList: std::vector<std::pair<uuid, uuid>>): std::vector<uuid, Route> // <vehicleId, route>
  +dispatchRoutes(routeList: std::vector<std::pair<uuid, Route>>): void
}

VehicleState -> TaxiStatus
WebApplication --> Scheduler : "Send ride request/change messages"
Scheduler --> FleetStateTracker : "Read fleet state"
FleetStateTracker --> Database : "Read/Write data"
Scheduler --> Commander : "Send/Read priority queue of ride requests"
Commander --> Router
Commander --> Robotaxi: "Send a route to Robotaxi"
FleetStateTracker --> Robotaxi : "Query vehicle state"


@enduml