@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
'!include C4_Container.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title System Context diagram for Internet Banking System

Person(p1, "Passenger", "Primary Actor")

Person(p2, "Dispatcher", "Secondary Actor")

System(FMS, "Fleet Management System", "Robotaxi System")

System_Ext(robo1, "Robotaxi [1]", "Secondary Actor")

Rel(p1, p2, "Request a ride", "phone call")
Rel(p1, p2, "Cancel a ride", "phone call")

Rel(p2, FMS, "Enter a ride request", "Console / Web")
Rel(p2, FMS, "Remove a ride request", "Console / Web")

Rel(FMS, robo1, "Assign a job", "Cellular Network")
Rel(FMS, robo1, "Cancel a job", "Cellular Network")

Rel(FMS, robo1, "Query vehicle state", "Cellular")
Rel(robo1, FMS, "Send vehicle state", "Cellular")

System_Boundary() {
    Container(FMS, "Fleet Management System", "Robotaxi System", "Java")
    Container(robo1, "Robotaxi [1]", "Robotaxi System", "C++")
    Container(robo2, "Robotaxi [2]", "Robotaxi System", "C++")
    Container(robon, "Robotaxi [N]", "Robotaxi System", "C++")
}

@enduml
