@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title System Context diagram for Internet Banking System

Person(p1, "Passenger", "Primary Actor")

Person(p2, "Dispatcher", "Secondary Actor")

System(FMS, "Fleet Management System", "Robotaxi System")

System_Ext(Map, "Map", "3rd party map")

System_Ext(robo1, "Robotaxi [1]", "Secondary Actor")
System_Ext(robo2, "Robotaxi [2]",  "Secondary Actor")
System_Ext(robon, "Robotaxi [N]",  "Secondary Actor")


Rel(p1, p2, "Request/Cancel a ride")

Rel(p2, FMS, "Enter/Remove a ride request")

Rel(FMS, robo1, "Assign/Cancel a job")
Rel(FMS, robo2, "Assign/Cancel ...")
Rel(FMS, robon, "Assign/Cancel ...")

Rel(FMS, robo1, "Query/Retrieve vehicle state")
Rel(FMS, robo2, "Query/Retrieve ...")
Rel(FMS, robon, "Query/Retrieve ...")

Rel(FMS, Map, "Query/Retrieve map data")

@enduml