@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/msql_server.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title System Context diagram for Internet Banking System

Person(p1, "Passenger", "Primary Actor")

Person(p2, "Dispatcher", "Secondary Actor")

System(FMS, "Fleet Management System", "Robotaxi System")

Rel(p1, p2, "Request/Cancel a ride", "Cellular Network")

System_Boundary(FMS, "Fleet Management System") {
    Container(Web, "Java", "Web Application", "Allow user to view, enter and edit ride request information")
    Container(API, "API", "Java", "Send commands to and query vehicle state from the whole fleet")
    ContainerDb(db, "Database", "Mongo DB", "Holds all data and metadata for passenger, ride, and vehicle", $sprite="msql_server")
}

Boundary(b2, "Robotaxi Fleet") {
    Container(robo1, "Robotaxi [1]", "Robotaxi System", "C++")
    Container(robo2, "Robotaxi [2]", "Robotaxi System", "C++")
    Container(robon, "Robotaxi [N]", "Robotaxi System", "C++")
}

Rel(p2, Web, "Enter/Remove a ride request", "https")

Rel(API, db, "Read/Write data", "JDBC")


Rel(API, robo1, "Assign/Cancel a job", "Cellular")
Rel(API, robo2, "...", "Cellular")
Rel(API, robon, "...", "Cellular")

Rel(API, robo1, "Query vehicle state", "Cellular")
Rel(API, robo2, "...", "Cellular")
Rel(API, robon, "...", "Cellular")

footer drawn with PlantUML v. %version() and C4-PlantUML v. C4Version()

@enduml
